//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CareUnit()
        {
            this.CareRequests = new HashSet<CareRequest>();
            this.CareUnitMembershipRequests = new HashSet<CareUnitMembershipRequest>();
            this.CareUnitRatings = new HashSet<CareUnitRating>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ProviderID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> AvailableRoomCount { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public long CareUnitTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareRequest> CareRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareUnitMembershipRequest> CareUnitMembershipRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareUnitRating> CareUnitRatings { get; set; }
        public virtual CareUnitType CareUnitType { get; set; }
        public virtual MedicalPlace MedicalPlace { get; set; }
    }
}
