//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareRequest
    {
        public long ID { get; set; }
        public long RequestMakerID { get; set; }
        public long MedicalPlaceID { get; set; }
        public long CareUnitID { get; set; }
        public string CaseDescription { get; set; }
        public long StatusID { get; set; }
        public System.DateTime RequestTime { get; set; }
        public bool IsConfirmed { get; set; }
    
        public virtual CareUnit CareUnit { get; set; }
        public virtual MedicalPlace MedicalPlace { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
