
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class CareUnitRating
{

    public long CitizenID { get; set; }

    public long CareUnitID { get; set; }

    public Nullable<int> Rating { get; set; }



    public virtual CareUnit CareUnit { get; set; }

    public virtual Citizen Citizen { get; set; }

}

}
