
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class Medicine
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Medicine()
    {

        this.Doses = new HashSet<Dose>();

        this.MedicineActiveIngredients = new HashSet<MedicineActiveIngredient>();

        this.PharmacyMedicines = new HashSet<PharmacyMedicine>();

        this.ReceiptMedicines = new HashSet<ReceiptMedicine>();

    }


    public long ID { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public long FormID { get; set; }

    public int ShelfLife { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dose> Doses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MedicineActiveIngredient> MedicineActiveIngredients { get; set; }

    public virtual MedicineForm MedicineForm { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PharmacyMedicine> PharmacyMedicines { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReceiptMedicine> ReceiptMedicines { get; set; }

}

}
