//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmacy()
        {
            this.PharmacyMedicines = new HashSet<PharmacyMedicine>();
            this.PharmacyRatings = new HashSet<PharmacyRating>();
            this.PharmacyMembershipRequests = new HashSet<PharmacyMembershipRequest>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> OwnerID { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public byte[] Photo { get; set; }
        public bool IsConfirmed { get; set; }
        public byte[] Permission { get; set; }
        public Nullable<long> MedicalPlaceID { get; set; }
    
        public virtual MedicalPlace MedicalPlace { get; set; }
        public virtual Specialist Specialist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyMedicine> PharmacyMedicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyRating> PharmacyRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyMembershipRequest> PharmacyMembershipRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
