
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class PharmacyMedicine
{

    public long PharmacyID { get; set; }

    public long MedicineID { get; set; }

    public Nullable<int> Quantity { get; set; }



    public virtual Medicine Medicine { get; set; }

    public virtual Pharmacy Pharmacy { get; set; }

}

}
