//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PotentialDisease
    {
        public long ID { get; set; }
        public long CitizenID { get; set; }
        public long DiseaseID { get; set; }
        public int Level { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Disease Disease { get; set; }
    }
}
