//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ReceiptMedicines = new HashSet<ReceiptMedicine>();
        }
    
        public long ID { get; set; }
        public long PharmacyID { get; set; }
        public long PharmacistID { get; set; }
        public long CitizenID { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Pharmacy Pharmacy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptMedicine> ReceiptMedicines { get; set; }
        public virtual Specialist Pharmacist { get; set; }
    }
}
