//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRating
    {
        public long CitizenID { get; set; }
        public long ServiceID { get; set; }
        public Nullable<double> Rating { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Service Service { get; set; }
    }
}
