
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
    using System.Collections.Generic;
    
public partial class SOSs
{

    public long ID { get; set; }

    public string Description { get; set; }

    public System.Data.Entity.Spatial.DbGeography Location { get; set; }

    public System.DateTime Time { get; set; }

    public bool IsAccepted { get; set; }

    public long StatusID { get; set; }

    public long SenderID { get; set; }

    public Nullable<long> MedicalPlaceID { get; set; }



    public virtual Citizen Sender { get; set; }

    public virtual MedicalPlace MedicalPlace { get; set; }

    public virtual RequestStatus RequestStatus { get; set; }

}

}
